apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
    pod-template-hash: 7fb96c846b
  name: nginx-deployment-7fb96c846b
  namespace: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      pod-template-hash: 7fb96c846b
  template:
    metadata:
      labels:
        app: nginx
        pod-template-hash: 7fb96c846b
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
