apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
  - name: editor
    image: python:3.7
    tty: true
    volumeMounts:
        - mountPath: "/myPV"
          name: test-storage
  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: test-claim
