apiVersion: v1
kind: Pod
metadata:
  name: nginx-mounted
  namespace: hello
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-var
              key: http_proxy
              optional: true # mark the variable as optional
      envFrom:
        - configMapRef:
            name: env-vars
      volumeMounts:
      - name: config-volume
        mountPath: /usr/share/nginx/html
  volumes:
    - name: config-volume
      configMap:
        name: my-html-file
