apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-mounted
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: key-var
              key: key_val
      volumeMounts:
      - name: secret-volume
        mountPath: /usr/share/nginx/html
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret-html-file
        optional: true
